### PR TITLE
Fix url parse at nested routers

### LINKED ISSUE #241: Fail to parse a nested url route
# The Problem
I'm using the openapi-tester with a file schema.yml loader, when a test a nested router ([drf-nested-routers](https://github.com/alanjds/drf-nested-routers)), for example, `/v1/matchs/1/maps/1/playerStats/` . I get a error of undocumented route. At the error message, we can see that the pks at the path was wrong position parsed.

# The Error Message
```
======================================================================
ERROR: test_list_all_playerStats (game.tests.test_view_playerStats.PlayerStatsViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/miniconda3/envs/hintclub-api/lib/python3.7/site-packages/openapi_tester/schema_tester.py", line 82, in get_key_value
    return schema[key]
KeyError: '/v1/matchs/{map_pk}/maps/{match_pk}/playerStats/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/***********/Documents/vscode_workspace/***********/game/tests/test_view_playerStats.py", line 124, in test_list_all_playerStats
    self.assertResponse(response)
  File "/Users/***********/Documents/vscode_workspace/***********/common/tests.py", line 14, in assertResponse
    schema_tester.validate_response(response=response, **kwargs)
  File "/opt/miniconda3/envs/hintclub-api/lib/python3.7/site-packages/openapi_tester/schema_tester.py", line 349, in validate_response
    response_schema = self.get_response_schema_section(response)
  File "/opt/miniconda3/envs/hintclub-api/lib/python3.7/site-packages/openapi_tester/schema_tester.py", line 124, in get_response_schema_section
    f"\n\nUndocumented route {parameterized_path}.\n\nDocumented routes: " + "\n\t• ".join(paths_object.keys()),
  File "/opt/miniconda3/envs/hintclub-api/lib/python3.7/site-packages/openapi_tester/schema_tester.py", line 86, in get_key_value
    ) from e
openapi_tester.exceptions.UndocumentedSchemaSectionError: Error: Unsuccessfully tried to index the OpenAPI schema by `/v1/matchs/{map_pk}/maps/{match_pk}/playerStats/`. 

Undocumented route /v1/matchs/{map_pk}/maps/{match_pk}/playerStats/.

Documented routes:  /v1/matchs/{match_pk}/maps/{map_pk}/playerStats/
```

# The Possible Solution

At line 137 is executed a right string search `rfind`, so the dictionary should be reversed like this `reversed(list(resolved_route.kwargs.items())`.

https://github.com/snok/drf-openapi-tester/blob/e2bd0aba2038aafff4d656cb8670a580ea7b951e/openapi_tester/loaders.py#L118-L148

### PR DESCRIPTION
**Pull request by igormaraujo**
close #241

### CODE REVIEW

**Comment by igormaraujo** [comment]
I wrote one test to check the fix only for static loaders. This is my first time doing a PR for a public project, so I tried to do my best. If I did something wrong or there is something to improve, just let me know.

**Comment by JonasKs** [comment]
Awesome!   
If you look at the [contributing guide](https://github.com/snok/drf-openapi-tester/blob/master/CONTRIBUTING.md), you’ll see that we use pre-commit. Two checks fails, one missing type annotation and one import statement order failure, as you can see in the failed pipeline. 

You can run pre-commit on all files by issuing the command: `pre-commit run —all-files` 😊

Let us know if there are any questions.

**Comment by sondrelg** [comment]
This looks good. Thanks @igormaraujo 👏  I'll release a new patch version shortly.

**Comment by Goldziher** [comment]
cheers

**Pull request merged**
