### PR TITLE
Avoid KeyError when utilizing additionalProperties=true

### PR DESCRIPTION
**Pull request by alexpaulzor**

### CODE REVIEW

**Comment by sondrelg** [comment]
Hi @alexpaulzor!

Can you explain a little bit about the motivation for this change? What's not behaving as expected, and do you have some code to illustrate?

**Comment by alexpaulzor** [comment]
Ok @sondrelg I was finally able to get unit tests running locally and I added a simple test that fails without my change, but works with it. Thank you, and I'm sorry it took so long.

**Comment by sondrelg** [comment]
Thanks a lot @alexpaulzor, this looks good to me! 👏 

I'll release a new version right away 🙂

**Comment by sondrelg** [comment]
Released v1.3.10 now with the fix 👍

**Pull request merged**
